In [30]:
import torch
import tensorflow as tf

#### Tensor
It's a possibly multidimensional array of numerical values.
- Vector - has one axis.
- Matrix - has 2 axes.
- k^{th} order tensor: k > 2.

In [31]:
torch_vector = torch.arange(12, dtype=torch.float32)
torch_vector 

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [32]:
tf_vector = tf.range(12, dtype=tf.float32)
tf_vector

<tf.Tensor: shape=(12,), dtype=float32, numpy=
array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
      dtype=float32)>

### size 
- The tensor contains 12 elements. We can inspect the total number of elements on each axis 

In [33]:
torch_vector.shape

torch.Size([12])

In [34]:
tf_vector.shape

TensorShape([12])

### reshape 
- we can change vector to matrix 

- In PyTorch, the shape of a tensor is represented using a list-like object ([])
- In TensorFlow, the shape is represented using a tuple (())
- This is a standard difference between the two frameworks

In [35]:
torch_matrix = torch_vector.reshape(3, 4)
print(torch_matrix)
print(torch_matrix.shape)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
torch.Size([3, 4])


In [36]:
tf_matrix = tf.reshape(tf_vector, (3, 4))

print(tf_matrix)
print(tf_matrix.shape)

tf.Tensor(
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]], shape=(3, 4), dtype=float32)
(3, 4)


### zeros or ones
- same syntax
  

In [37]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [38]:
tf.ones((2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

#### we can also randomise 
- or no 
  

In [39]:
torch.randn(3, 4)

tensor([[ 1.0692,  0.1560, -0.7753, -1.0152],
        [-1.3816, -0.5573,  0.6731,  0.0739],
        [-0.9312,  0.7023, -0.7129,  1.2132]])

In [40]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [41]:
tf.random.normal(shape=[3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.46319243,  0.46011356,  1.0103424 ,  0.33137318],
       [ 0.9240539 , -0.69257766, -1.5730792 ,  0.07218122],
       [ 0.6786363 , -0.95819926,  2.3878708 ,  0.26408756]],
      dtype=float32)>

In [42]:
tf.constant([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]])>

# Indexing and Slicing

In [ ]:
# we acces with given index in order rows, columns
torch_matrix[1, 2]

tensor(6.)

In [ ]:
# we acces <1, 3) range of rows
torch_matrix[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
torch_matrix[0:2] 

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [46]:
torch_matrix[2, 3] = 99
torch_matrix

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 99.]])

In [47]:
torch_matrix[1]

tensor([4., 5., 6., 7.])

In [ ]:
# we can use : as a wildcard for all elements or x: for all elements from x to the end
torch_matrix[1:, :] = 2
torch_matrix

tensor([[0., 1., 2., 3.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

In [51]:
torch_matrix[:2, :2] = 0
torch_matrix 

tensor([[0., 0., 2., 3.],
        [0., 0., 3., 4.],
        [5., 6., 7., 8.]])

# Operations


In [53]:
torch_vector = torch.arange(12, dtype=torch.float32)
torch_vector

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
# we e^x every element of the vector
torch.exp(torch_vector)

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04])

In [ ]:
# basicly linear algebra, we will come back to this in 2.3
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [ ]:
# we setup 2 same size matrices
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X, Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [ ]:
# cat is short for concatenate, we concatenate the 2 matrices
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [61]:
# boolean operations
X == Y, X < Y, X > Y

(tensor([[False,  True, False,  True],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]))

In [60]:
X.sum()

tensor(66.)

# Broadcasting

- broadcasting mechanism - its a way tensors fill as we try to add 2 with diffrent shapes


In [ ]:
# we make 3,1 and 1,2 matrices
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [ ]:
# now we add them, this is called broadcasting 
# - what happens is a is "strecehd" to 3,2 matrix and b is "stretched" to 3,2 matrix 
# - so a copies its elements to 2nd column and b copies its elements to 2nd and 3rd row
# - then we add them together
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [77]:
# lets try 3 dimensional matrices
A = torch.arange(24).reshape(2, 3, 4)
B = torch.tensor([0, 1, 0, 1])
A, B

# we add them together, this is called broadcasting
A + B

# yeah it works with more dimensions


tensor([[[ 0,  2,  2,  4],
         [ 4,  6,  6,  8],
         [ 8, 10, 10, 12]],

        [[12, 14, 14, 16],
         [16, 18, 18, 20],
         [20, 22, 22, 24]]])

# Memory

In [ ]:
# set up
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [ ]:
# what happenes is 
# - python checks if X and Y are the same size
# - evaluates X + Y
# - alocates new memory for the result
# - copies the result to the new memory
# - returns the new memory
# - the old memory is dealocated by the garbage collector
# - this is slow 

before = id(Y)
Y = Y + X
id(Y) == before

False

In [ ]:
# we can impove it by using the : operator
# eventually we we can use the += operator

before = id(X)
X[:] = X + Y # same as X += Y
id(X) == before


True

In [68]:
# we can use it for other operations as well

Z = torch.zeros_like(Y) # we create a matrix with the same shape as Y
before = id(Z)
Z[:] = X + Y
id(Z) == before


True

# Conversion to Other Python Objects

In [69]:
# we setup 2 matrices
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [71]:
A = X.numpy()
B = torch.tensor(A)
C = torch.from_numpy(A)
type(A), type(B), type(C)

(numpy.ndarray, torch.Tensor, torch.Tensor)

In [72]:
# To convert a size-1 tensor to a Python scalar, we can invoke the item function or Python’s built-in functions. 
# seems useless but aparrently it is not
a = torch.tensor([3.5])

a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)