In [26]:
import torch
import tensorflow as tf

#### Tensor
It's a possibly multidimensional array of numerical values.
- Vector - has one axis.
- Matrix - has 2 axes.
- k^{th} order tensor: k > 2.

In [27]:
torch_vector = torch.arange(12, dtype=torch.float32)
torch_vector 

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [28]:
tf_vector = tf.range(12, dtype=tf.float32)
tf_vector

<tf.Tensor: shape=(12,), dtype=float32, numpy=
array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
      dtype=float32)>

### size 
- The tensor contains 12 elements. We can inspect the total number of elements on each axis 

In [29]:
torch_vector.shape

torch.Size([12])

In [30]:
tf_vector.shape

TensorShape([12])

### reshape 
- we can change vector to matrix 

- In PyTorch, the shape of a tensor is represented using a list-like object ([])
- In TensorFlow, the shape is represented using a tuple (())
- This is a standard difference between the two frameworks

In [31]:
torch_matrix = torch_vector.reshape(3, 4)
print(torch_matrix)
print(torch_matrix.shape)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
torch.Size([3, 4])


In [32]:
tf_matrix = tf.reshape(tf_vector, (3, 4))

print(tf_matrix)
print(tf_matrix.shape)

tf.Tensor(
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]], shape=(3, 4), dtype=float32)
(3, 4)


### zeros or ones
- same syntax
  

In [42]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [43]:
tf.ones((2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

#### we can also randomise 
- or no 
  

In [44]:
torch.randn(3, 4)

tensor([[-1.9599, -0.8767,  0.9967,  0.2498],
        [ 0.4178, -0.4187,  1.6108, -2.2183],
        [ 0.4479, -0.9994,  0.0068,  0.1921]])

In [45]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [46]:
tf.random.normal(shape=[3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.58013225,  0.9572984 , -0.32949087,  0.8125786 ],
       [-0.19561785, -0.39825487, -0.42751333,  0.6381588 ],
       [ 0.07143695,  0.5351988 ,  1.293703  , -1.3997437 ]],
      dtype=float32)>

In [47]:
tf.constant([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]])>